#!/usr/bin/env python

import sys

from gui_arm_us.gui_arm_us_Plugin import GuiArmUsPlugin
from rqt_gui.main import Main

plugin = 'gui_arm_us'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
