left_joy_hori: 0
left_joy_vert: 1
left_trig: 2
right_joy_hori: 3
right_joy_vert: 4
right_trig: 5
pad_hori: 6
pad_vert: 7

button_a: 0
button_b: 1
button_x: 2
button_y: 3
left_bump: 4
right_bump: 5

name: "mik"