j1:
  max_limit: 180.0
  min_limit: -180.0

  pos_max_angle: 4096.0
  pos_min_angle: 0.0

j2:
  max_limit: 180.0
  min_limit: -180.0

  pos_max_angle: 4096.0
  pos_min_angle: 0.0

j3:
  max_limit: 180.0
  min_limit: -180.0

  pos_max_angle: 4096.0
  pos_min_angle: 0.0

j4:
  max_limit: 180.0
  min_limit: -180.0

  pos_max_angle: 4096.0
  pos_min_angle: 0.0

j5:
  max_limit: 180.0
  min_limit: -180.0

  pos_max_angle: 4096.0
  pos_min_angle: 0.0
